### ISSUE TITLE
Wrapped list items are not recognized

### ISSUE THREAD

**Issue by jimwise** [calvinwyoung/org-autolist#10]
Given this list:

```
- general rules:
  - even newcomers are bound by trade usage once it is established that
    something *is* a trade usage[HERE]
```

Hitting enter at [HERE] does not create a new list item, even though this is a valid org list.

Please advise

**Comment by joelostblom** [comment]
I see this problem as well, @jimwise did you find a workaround?

**Comment by jimwise** [comment]
So far, just got used to it.  But would love a fix, if easy to do.

**Comment by calvinwyoung** [comment]
Hey guys, sorry to leave this one hanging. I got pretty busy with work around the time this was posted and somehow lost track of it. Let me take a look at it in the next couple of days and see if I can figure out a fix.

**Comment by joelostblom** [comment]
@calvinwyoung Thank you!

I believe the problem is that `org-at-item-p` does not evaluate to `t` for hard wrapped lists (except for the first line). `org-meta-return` seems to do the right thing and continue the hard wrapped list, so if there is a way to detect whether the first line of the paragraph starts with a bullet point and then send `org-meta-return` that could be a possible solution (I think... still quite new to emacs =p).

**Comment by joelostblom** [comment]
Actually, I believe all you have to do is to use `org-in-item-p` instead of `org-at-item-p`.

**Comment by chongchonghe** [comment]
My impression is spacemacs doesn't have this problem. Perhaps worth to take a look at their solution.
